# Generated by Django 5.2.17 on 2026-10-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='position',
        ),
    ]
