# Generated by Django 5.2.17 on 2026-10-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='check_follows',
            new_name='check_follower',
        ),
    ]
