# Generated by Django 5.2.17 on 2026-10-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], max_length=8),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', '-created_at'], name='accounts_fo_followi_0cee87_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='no_self_follow'),
        ),
    ]
